-- DDL to store the user requests

CREATE TABLE IF NOT EXISTS forex_schema.forex_trend_history (
	id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	request_date date NULL,
	base_currency varchar(255) NULL,
	target_currency varchar(255) NULL,
	forex_rate float8 NULL,
	trend VARCHAR(100) NULL,
	trend_end_date date NULL,
	trend_start_date date NULL,
	historical_average float8 NULL,
	query_timestamp timestamp DEFAULT now(),
	CONSTRAINT forex_trend_history_pkey PRIMARY KEY (id)
);


ALTER TABLE forex_schema.forex_trend_history OWNER TO $FOREX_DB_USER$;